<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * signals
 *
 * Trading signals generated by our analysis engine.
 * A signal says: "based on edge analysis, BUY YES / BUY NO at this price."
 *
 * Design decisions:
 * - A signal is generated when edge exceeds our minimum threshold.
 * - Signals are decoupled from paper trades: one signal can spawn one
 *   paper trade, but the signal itself just captures the analytical event.
 * - `direction` is 'yes' | 'no' — we're buying a position in a binary market.
 * - `trigger_source` documents what created this signal:
 *   'manual', 'edge_threshold', 'ai_engine' — lets us evaluate which
 *   source generates the best signals over time.
 * - `edge_at_signal` is the edge when the signal fired. Market conditions
 *   change; we need to record the state at decision time.
 * - `min_edge_threshold` is our configured minimum edge for this signal —
 *   allows tracking whether we lowered/raised thresholds over time.
 * - `status` lifecycle: pending → active → closed | cancelled
 * - Soft deletes so we never lose signal history.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('signals', function (Blueprint $table) {
            $table->id();

            $table->foreignId('market_id')
                ->constrained('markets')
                ->cascadeOnDelete();

            // Optional FK to the AI prediction that generated this signal
            $table->foreignId('ai_prediction_id')
                ->nullable()
                ->constrained('ai_predictions')
                ->nullOnDelete()
                ->comment('Set when AI engine triggers the signal; NULL for rule-based signals');

            // Signal direction
            $table->string('direction', 10)
                ->comment('yes | no — which side we are signalling');

            // Edge at time of signal
            $table->decimal('market_probability_at_signal', 8, 6)
                ->comment('Market probability when signal was generated');
            $table->decimal('ai_probability_at_signal', 8, 6)->nullable()
                ->comment('AI probability when signal was generated (NULL if rule-based)');
            $table->decimal('edge_at_signal', 8, 6)
                ->comment('Edge when signal fired (positive = favourable)');
            $table->decimal('confidence_at_signal', 8, 6)->nullable()
                ->comment('AI confidence at signal time');

            // Signal configuration
            $table->decimal('min_edge_threshold', 8, 6)->default(0.05)
                ->comment('Minimum edge configured when signal fired');
            $table->string('trigger_source', 50)->default('edge_threshold')
                ->comment('edge_threshold | ai_engine | manual');

            // Lifecycle
            $table->string('status', 30)->default('pending')
                ->comment('pending | active | closed | cancelled');
            $table->text('notes')->nullable();
            $table->timestamp('fired_at')
                ->comment('When the signal was generated');
            $table->timestamp('expires_at')->nullable()
                ->comment('Signals for time-sensitive markets expire');

            $table->timestamps();
            $table->softDeletes();
        });

        Schema::table('signals', function (Blueprint $table) {
            $table->index(['market_id', 'status'], 'signals_market_status_idx');
            $table->index(['status', 'fired_at'], 'signals_status_fired_idx');
            $table->index('edge_at_signal', 'signals_edge_idx');
            $table->index('direction', 'signals_direction_idx');
            $table->index('trigger_source', 'signals_source_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('signals');
    }
};
